name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  rust:
    runs-on: selfrunners
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Format
        run: cargo fmt --all -- --check
      - name: Check
        run: cargo check --workspace
      - name: Test
        run: cargo test --workspace